### ISSUE TITLE
Error in ROI-drawing tutorial

### ISSUE THREAD

**Issue by htakemur** [noahbenson/neuropythy-tutorials#1]
Hello Noah,

I am now trying your ROI-drawing tutorial on my computer, by loading hemispheres of HCP data on Jupiter notebook. 

I got a following error, when I executed a following command:
`ny.cortex_plot(flatmap, color='prf_polar_angle', mask=('prf_variance_explained', 0.1, 1),
               axes=ax)`

May I ask you to give me some thoughts? 

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-14-60d7983f610f> in <module>
      3 (fig,ax) = plt.subplots(1,1, figsize=(3.5,3.5), dpi=4*72)
      4 ny.cortex_plot(flatmap, color='prf_polar_angle', mask=('prf_variance_explained', 0.1, 1),
----> 5                axes=ax)
      6 ax.axis('equal')
      7 ax.axis('off')

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/graphics/core.py in cortex_plot(mesh, *args, **opts)
   1339         return cortex_plot_3D(mesh, *args, **opts)
   1340     else:
-> 1341         return cortex_plot_2D(mesh, *args, **opts)
   1342 
   1343 class ROIDrawer:

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/graphics/core.py in cortex_plot_2D(the_map, color, cmap, vmin, vmax, alpha, underlay, mask, axes, triangulation)
   1118     # process the colors
   1119     color = cortex_plot_colors(the_map, color=color, cmap=cmap, vmin=vmin, vmax=vmax, alpha=alpha,
-> 1120                                underlay=underlay, mask=mask)
   1121     # finally, we can make the plot!
   1122     return cortex_rgba_plot_2D(the_map, color, axes=axes, triangulation=triangulation)

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/graphics/core.py in cortex_plot_colors(the_map, color, cmap, vmin, vmax, alpha, underlay, mask)
   1020     if pimms.is_vector(color) or pimms.is_str(color):
   1021         # it's a property that gets interpreted via the colormap
-> 1022         p = the_map.property(color)
   1023         # if the colormap is none, we can try to guess it
   1024         logtr = False

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/geometry/mesh.py in property(self, prop, dtype, outliers, data_range, clipped, weights, weight_min, weight_transform, mask, valid_range, null, transform, yield_weight)
    163                            weight_min=weight_min, weight_transform=weight_transform,
    164                            mask=mask,             valid_range=valid_range,
--> 165                            transform=transform,   yield_weight=yield_weight)
    166     def property_search(self, *patterns, **kw):
    167         '''

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/geometry/mesh.py in to_property(obj, prop, dtype, outliers, data_range, clipped, weights, weight_min, weight_transform, mask, valid_range, null, transform, yield_weight)
    496     if pimms.is_str(prop):
    497         if obj is None: raise ValueError('a property name but no data object given to to_property')
--> 498         else: prop = obj[prop]
    499     if is_set(prop):
    500         def _lazy_prop(kk):

~/opt/anaconda3/lib/python3.7/site-packages/pimms/table.py in __getitem__(self, rows, cols)
    368             return self.rows[rows]
    369         elif isinstance(rows, six.string_types):
--> 370             return self.data[rows]
    371         elif rows is None or len(rows) == 0:
    372             return ITable(ps.m(), n=0)

~/opt/anaconda3/lib/python3.7/site-packages/pimms/util.py in __getitem__(self, k)
    787             return val
    788     def __getitem__(self, k):
--> 789         return self._examine_val(k, ps.PMap.__getitem__(self, k))
    790     def iterkeys(self):
    791         for (k,_) in ps.PMap.iteritems(self):

~/opt/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in __getitem__(self, key)
     69 
     70     def __getitem__(self, key):
---> 71         return PMap._getitem(self._buckets, key)
     72 
     73     @staticmethod

~/opt/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in _getitem(buckets, key)
     66                     return v
     67 
---> 68         raise KeyError(key)
     69 
     70     def __getitem__(self, key):

KeyError: 'prf_polar_angle'`

**Comment by T-Miya038** [comment]
Hi Noah, 

We have to also add that we failed to install bumpy... but we don't know whether it is necessary to run your command.

Best,
Toshikazu

**Comment by noahbenson** [comment]
So the `bumpy` library is a typo--should be `numpy`; where did you find `bumpy`? That bug is easy to fix.

I am looking into the `KeyError` but it may indicate that there is a problem reading in the retinotopy data.

**Comment by noahbenson** [comment]
Actually, if `bumpy` is a typo or auto-correct (i.e., if you were unable to install `numpy`) then this is probably the source of both errors; the latter error might be happening because it can't use numpy to read in or to process the PRF data.

**Comment by htakemur** [comment]
First, we checked installation of numpy -- and confirmed that numpy is installed:

`Name: numpy
Version: 1.18.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /Users/takemura/opt/anaconda3/lib/python3.7/site-packages
Requires: 
Required-by: tables, statsmodels, seaborn, scipy, scikit-learn, PyWavelets, pythreejs, pytest-arraydiff, pimms, patsy, pandas, numexpr, numba, nibabel, neuropythy, mkl-random, mkl-fft, matplotlib, ipyvolume, ipydatawidgets, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy
`

I guess that bumpy is a typo when I took a note of required python package. Sometimes, automated spell checker tries to fix "numpy" to "bumpy"...  

I checked my notebook again, and we think that we rightly loaded numpy:
`import numpy as np`

Then we checked loaded variables by following commands: 

`
In[15]: hem

Out[15]: Cortex(<LH>, <303596 faces>, <151800 vertices>)

In[16]:flatmap

Out[16]Mesh(<2D>, <73880 faces>, <37193 vertices>)
`

Therefore, it looks like that hemisphere/surface is loaded without error, and flatmap was calculated without error. 

I guess that one possibility is that the output depends upon coordinates of loaded hemispheres (e.g. native vs. fs average), and compatibility of the code loading pRF data from each coordinate space. 

In this test, we simply aimed to follow tutorial, as similar as we can:

`
In[9]: sid = 100610

In[10]: sub = ny.hcp_subject(sid)

In[11]: h = 'lh'

In[12]: hem = sub.hemis[h]

In[13]:flatmap = ny.to_flatmap('occipital_pole', hem) 
`

We appreciate if you share any thoughts!

**Comment by noahbenson** [comment]
Okay, this is very helpful for understanding things. A few thoughts:
1. Probably there is something going wrong with the getting the pRF data loaded onto the hemisphere. I know we went through getting that to work awhile ago, so it seems unlikely that this is the issue unless you're on a different computer or have changed your paths around? What happens when you run just this:  
   ```python
   sub = ny.hcp_subject(100610)
   sub.lh.prop('prf_polar_angle').shape
   ```
2. Can you send me the output of `ny.__version__`? I just want to make sure we are looking at the same code.
3. If the code in 1 worked and gave you back something like `(163251,)` (or some number close to that), then it's a flatmap issue, but if not, try this:
   ```
   hem = sub.hemis['lh_LR32k_MSMAll']
   hem.prop('lowres-prf_polar_angle').shape
   ```

**Comment by htakemur** [comment]
Hello @noahbenson 

Thank you very much for your support! 

1. I got similar error, so that it is likely that there is something wrong with getting pRF data on this hemisphere:

```
sub = ny.hcp_subject(100610)
sub.lh.prop('prf_polar_angle').shape

KeyError                                  Traceback (most recent call last)
<ipython-input-18-0bf1f7db81c9> in <module>
----> 1 sub.lh.prop('prf_polar_angle').shape

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/geometry/mesh.py in prop(self, name)
    118         '''
    119         if pimms.is_str(name):
--> 120             return self.properties[name]
    121         elif is_set(name):
    122             return pyr.pmap({nm:self.properties[nm] for nm in name})

~/opt/anaconda3/lib/python3.7/site-packages/pimms/table.py in __getitem__(self, rows, cols)
    368             return self.rows[rows]
    369         elif isinstance(rows, six.string_types):
--> 370             return self.data[rows]
    371         elif rows is None or len(rows) == 0:
    372             return ITable(ps.m(), n=0)

~/opt/anaconda3/lib/python3.7/site-packages/pimms/util.py in __getitem__(self, k)
    787             return val
    788     def __getitem__(self, k):
--> 789         return self._examine_val(k, ps.PMap.__getitem__(self, k))
    790     def iterkeys(self):
    791         for (k,_) in ps.PMap.iteritems(self):

~/opt/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in __getitem__(self, key)
     69 
     70     def __getitem__(self, key):
---> 71         return PMap._getitem(self._buckets, key)
     72 
     73     @staticmethod

~/opt/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in _getitem(buckets, key)
     66                     return v
     67 
---> 68         raise KeyError(key)
     69 
     70     def __getitem__(self, key):

KeyError: 'prf_polar_angle'
```

2. It is "0.11.5"

3. Executing this comment produces similar error, as follows:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-20-2709fa4a1291> in <module>
      1 hem = sub.hemis['lh_LR32k_MSMAll']
----> 2 hem.prop('lowres-prf_polar_angle').shape

~/opt/anaconda3/lib/python3.7/site-packages/neuropythy/geometry/mesh.py in prop(self, name)
    118         '''
    119         if pimms.is_str(name):
--> 120             return self.properties[name]
    121         elif is_set(name):
    122             return pyr.pmap({nm:self.properties[nm] for nm in name})

~/opt/anaconda3/lib/python3.7/site-packages/pimms/table.py in __getitem__(self, rows, cols)
    368             return self.rows[rows]
    369         elif isinstance(rows, six.string_types):
--> 370             return self.data[rows]
    371         elif rows is None or len(rows) == 0:
    372             return ITable(ps.m(), n=0)

~/opt/anaconda3/lib/python3.7/site-packages/pimms/util.py in __getitem__(self, k)
    787             return val
    788     def __getitem__(self, k):
--> 789         return self._examine_val(k, ps.PMap.__getitem__(self, k))
    790     def iterkeys(self):
    791         for (k,_) in ps.PMap.iteritems(self):

~/opt/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in __getitem__(self, key)
     69 
     70     def __getitem__(self, key):
---> 71         return PMap._getitem(self._buckets, key)
     72 
     73     @staticmethod

~/opt/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in _getitem(buckets, key)
     66                     return v
     67 
---> 68         raise KeyError(key)
     69 
     70     def __getitem__(self, key):

KeyError: 'lowres-prf_polar_angle'
```

**Comment by htakemur** [comment]
Actually, I noticed that what could be the potential source... In fact, we switched a computer.

We have used a cluster computer (Ubuntu) for previous setting on HCP pRF... but we are uncomfortable to use Jupyter notebook in that environment by several reasons. Now we are running Jupyter notebook on Mac, and mounting cluster data directory in there. This changed the address of HCP directory. I will have a look and check...

**Comment by noahbenson** [comment]
Ahh, okay, that makes sense. Your errors are all consistent with something being wrong with the PRF data getting loaded in. The first thing I would check is that the file `prfresults.mat` is still in your HCP subjects directory (i.e., the directory that contains the subject directories like 100610/ and 111312/).

Also, this is just a hunch, but do you have write-permission in the HCP directories you are using? I don't think there should be an issue with this, but I haven't tested it either. If you don't have write permission, you could try copying just the directory for 100610 and the prfresults.mat file to another directory that you control, then try just loading subject 100610 from that directory and checking for the 'prf_polar_angle' data.

**Comment by htakemur** [comment]
I have changed a configuration, by typing 

'''
ny.config['hcp_subject_paths'] = '/Volumes/project/proj_htakemur/humandata/HCP_Retinotopy'
'''

and then configuration changed, and I think that my neuropythy now knows where HCP Retinotopy data exist. 
This directory (/Volumes/project/proj_htakemur/humandata/HCP_Retinotopy) also contains prfresults.mat. 

I still got the same error --- just as you suggest, I think that I should doubt permission. Actually it turns out that I don't have a permission, when I accessed this folder throughout the mounting process:

'''
drwx------  1 takemura  staff       16384  4  8 10:23 100610
'''

I will try to find out resolving the way to resolve a permission...

**Comment by noahbenson** [comment]
Okay, yeah, that might be it. Let me know if you can't find an easy solution and if the test I mentioned earlier about copying one subject's directory and the `prfresults.mat` file to a local directory where you have write-permission seems to fix it for that subject. If that's the case then I can figure out a solution.

**Comment by T-Miya038** [comment]
Hello @noahbenson 

We fixed permission issue, and also tested to copy both subject directory and the `prfresults.mat` into a new local directory where I have write-permission. However, in both cases, we still persistently got the same error. May I ask you to share some thoughts on this? 

----
In [28]: sub = ny.hcp_subject(100610)
             sub.lh.prop('prf_polar_angle').shape

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-474c7b258c25> in <module>
      1 sub = ny.hcp_subject(100610)
----> 2 sub.lh.prop('prf_polar_angle').shape

~/anaconda3/lib/python3.7/site-packages/neuropythy/geometry/mesh.py in prop(self, name)
    118         '''
    119         if pimms.is_str(name):
--> 120             return self.properties[name]
    121         elif is_set(name):
    122             return pyr.pmap({nm:self.properties[nm] for nm in name})

~/anaconda3/lib/python3.7/site-packages/pimms/table.py in __getitem__(self, rows, cols)
    368             return self.rows[rows]
    369         elif isinstance(rows, six.string_types):
--> 370             return self.data[rows]
    371         elif rows is None or len(rows) == 0:
    372             return ITable(ps.m(), n=0)

~/anaconda3/lib/python3.7/site-packages/pimms/util.py in __getitem__(self, k)
    787             return val
    788     def __getitem__(self, k):
--> 789         return self._examine_val(k, ps.PMap.__getitem__(self, k))
    790     def iterkeys(self):
    791         for (k,_) in ps.PMap.iteritems(self):

~/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in __getitem__(self, key)
     69 
     70     def __getitem__(self, key):
---> 71         return PMap._getitem(self._buckets, key)
     72 
     73     @staticmethod

~/anaconda3/lib/python3.7/site-packages/pyrsistent/_pmap.py in _getitem(buckets, key)
     66                     return v
     67 
---> 68         raise KeyError(key)
     69 
     70     def __getitem__(self, key):

KeyError: 'prf_polar_angle'
---------------------------------------------------------------------------

**Comment by noahbenson** [comment]
Hmm. I think it may require us meeting briefly with screen-share over zoom to debug this. However, first, can you try the following? It will almost certainly generate an error when you evaluate the first line, but I'm curious what the output is:

```python
sub = ny.data['hcp_retinotopy'].subjects[100610]
sub.lh.prop('prf_polar_angle')
```

**Comment by T-Miya038** [comment]
Hello @noahbenson
Thank you for your support.
We tried your command, but we still got the error.

-------------------------------------------------------------------------
sub = ny.data['hcp_retinotopy'].subjects[100610]
sub.lh.prop('prf_polar_angle')

--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-1a8d4f8e7734> in <module>
----> 1 sub = ny.data['hcp_retinotopy'].subjects[100610]
      2 sub.lh.prop('prf_polar_angle')

~/anaconda3/lib/python3.7/site-packages/pimms/util.py in __getitem__(self, k)
    787             return val
    788     def __getitem__(self, k):
--> 789         return self._examine_val(k, ps.PMap.__getitem__(self, k))
    790     def iterkeys(self):
    791         for (k,_) in ps.PMap.iteritems(self):

~/anaconda3/lib/python3.7/site-packages/pimms/util.py in _examine_val(self, k, val)
    783             return val
    784         else:
--> 785             val = val()
    786             object.__setattr__(self, '_memoized', self._memoized.set(vid, val))
    787             return val

~/anaconda3/lib/python3.7/site-packages/pimms/util.py in curried_f(*args, **kwargs)
    687     '''
    688     def curried_f(*args, **kwargs):
--> 689         return f(*(args0 + args), **merge(kwargs0, kwargs))
    690     return curried_f
    691 def is_seq(arg):

~/anaconda3/lib/python3.7/site-packages/neuropythy/datasets/hcp.py in _prep(sid)
    623                 sub = hcp._subjects[sid]
    624             except Exception: hcp = None
--> 625             if hcp is None: raise ValueError('could not load subject object for sid %s' % (sid,))
    626             # okay, we need to prep this subject; the initial part is easy: copy the properties
    627             # for the fs_LR meshes over to them:

ValueError: could not load subject object for sid 100610

**Comment by T-Miya038** [comment]
Updating neuropythy version fixed this problem. Thank you very much!
