### ISSUE TITLE
Flat maps visualization with retinotopic maps

### ISSUE THREAD

**Issue by felenitaribeiro** [noahbenson/neuropythy-tutorials#2]
Hi Noah,

I checked your roi-drawing tutorial to find out how to interpolate polar angle maps on the flat map, as in cell 5. Still, I noticed that the polar angle map is not aligned with the underlying occipital cortex. I'm a bit unsure how to correct that (it looks like the issue was already on the output of your tutorial).

I ran:

```
import neuropythy as ny
import matplotlib as mpl
import matplotlib.pyplot as plt

sub = ny.hcp_subject(105923)
lh = sub.lh
flatmap = ny.to_flatmap('occipital_pole', sub.hemis['lh'])


(fig,ax) = plt.subplots(1,1, figsize=(3.5,3.5), dpi=4*72)
ny.cortex_plot(flatmap, color='lowres-prf_polar_angle', mask=('lowres-prf_variance_explained', 0.1, 1),
               axes=ax, alpha=.25)
ax.axis('equal')
ax.axis('off')

pass
```

and got:

![output](https://github.com/noahbenson/neuropythy-tutorials/assets/33485379/3520cc87-ca1f-47bc-a22e-1b6eeac88ffa)

**Comment by noahbenson** [comment]
Hi Fernanda! I don't think we're seeing an error here—this subject just has a very posterior fovea. Let's compare a few plots:

### V1 Anatomical Label (from FreeSurfer), flatmap
```python
ny.cortex_plot(flatmap, color='r', mask='V1_label', alpha=0.5)
```
![image](https://github.com/noahbenson/neuropythy-tutorials/assets/2005723/eaf8f21a-ea76-4e86-a2ac-25f826038c8e)

### V1 Anatomical Label (from FreeSurfer), white surface
```python
ny.cortex_plot(lh, surface='white', color='r', mask='V1_label', alpha=0.5)
```
![image](https://github.com/noahbenson/neuropythy-tutorials/assets/2005723/bfe0026b-cbd4-4165-af88-e0352d9b49cb)

### Polar Angle, white surface
```python
ny.cortex_plot(lh, surface='white', color='prf_polar_angle',
               mask=('prf_variance_explained', 0.1, 1), alpha=.5)
```
![image](https://github.com/noahbenson/neuropythy-tutorials/assets/2005723/5e7cda25-a22d-435a-aec2-5c26c70849e5)

These all look fairly normal to me—the fovea of V2 and V3 is often highly posterior, even creeping toward being lateral. The V1 boundaries mostly line up with the gyri of the Calcarine Sulcus, but this leaves the V2 and V3 foveal confluences leaning toward the lateral side. Is there another issue you see here?

By the way: `lowres-prf_*` is the same as `prf_*` in the native HCP hemispheres—I included the `highres-prf_*` and `lowres-prf_*` initially as a placeholder for someone (probably me) eventually calculated the pRF solutions on the 59k surfaces (we used the 32k surfaces in the HCP 7T Retinotopy Dataset), thinking that when those PRF solutions became available, I'd just switch the `prf_*` properties over to using the 59k (highres) version. Nobody's done that calculation yet, though, so `prf_*` is an alias for `lowres-prf_*`.

**Comment by felenitaribeiro** [comment]
Yes, I see! Thank you! :100:
